name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK, Build-Tools & NDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31
          build-tools: '33.0.2'
          ndk: '23.1.7779620'

      - name: Export Android SDK/NDK paths
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/23.1.7779620" >> $GITHUB_ENV

      - name: Accept all Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install system deps & Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip python3-pip
          pip3 install --upgrade pip setuptools Cython virtualenv buildozer

      - name: Build APK
        run: buildozer android debug
