name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user buildozer cython

      - name: Fix Android SDK and Force Build Tools 33.0.2
        run: |
          echo "Setting up Android SDK environment"
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

          echo "Installing Build-Tools 33.0.2 and accepting licenses"
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2"

          echo "Verifying AIDL exists"
          ls $ANDROID_SDK_ROOT/build-tools/33.0.2/aidl || (echo "AIDL missing!" && exit 1)

          echo "Overriding PATH with correct build-tools version"
          export PATH=$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.2:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: bin/*.apk
