name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Cache Buildozer, SDK, NDK, and Python Environment
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.cache
            ~/.buildozer/android/platform/android-sdk
            ~/.buildozer/android/platform/android-ndk
            ~/.buildozer/android/app/code_cache
            .venv
          key: Linux-buildozer-Linux-python-${hashFiles('**/buildozer.spec', 'requirements.txt')}
          restore-keys: |
            Linux-buildozer-Linux-python-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python Dependencies and Buildozer
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U Cython kivy-deps
          pip install buildozer

      - name: Build APK (Debug)
        run: |
          source .venv/bin/activate
          buildozer -v android debug
        id: buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.apk_path }}
